apiVersion: v1
kind: Namespace
metadata:
  name: chat-bot

---
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-bot-deployment
  namespace: chat-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-bot
  template:
    metadata:
      labels:
        app: chat-bot
    spec:
      containers:
        - name: chat-bot-pod
          image: scholtz2/vote-coin-chatbot:1.0.2-stable
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2000Mi" 
          lifecycle:
            preStop:
              exec:
                command: ["sleep","30"]
          env:
            - name: token
              valueFrom:
                secretKeyRef:
                  name: settings-secret
                  key: token
            