# set base image (host OS)
FROM scholtz2/vote-coin-chatbot-base:1.0.0-stable

# set the working directory in the container
COPY . .

# command to run on container start
CMD [ "python", "./vote_coin_bot.py" ]